name: CI-CodableFeedStore

on:
  push:
    branches: [ merge-to-codable-feedstore ]

jobs:
  build-and-test:

    runs-on: macOS-11
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.0.app

    - name: Build and test
      run: xcodebuild clean build test -project EssentialFeed.xcodeproj -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
